### PR TITLE
Integrity#match bugfix and other optimizations

### LINKED ISSUE #41: [BUG] Integrity#match doesn't always find common algorithm
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

An input containing both sha1+sha512 matches an input with only sha1, but not vice versa:
```
const ssri = require('ssri')

const sha1 = 'sha1-X1UT+IIv2+UUWvM7ZNjZcNz5XG4='
const sha512 = 'sha512-yzd8ELD1piyANiWnmdnpCL5F52f10UfUdEkHywVZeqTt0ymgrxR63Qz0GB7TKPoeeZQmWCaz7T1+9vBnypkYWg=='
const both = sha1 + ' ' + sha512

// returns truthy
console.log('both,sha1=', ssri.parse(both).match(sha1))
// returns false
console.log('sha1,both=', ssri.parse(sha1).match(both))
```

### Expected Behavior

I would have expected both calls to return a truthy value, since they have an algorithm in common, and the hash matches.

### Steps To Reproduce

_No response_

### Environment

- ssri: 9.0.1
- Node: 16.15.1

### PR DESCRIPTION
**Pull request by wraithgar**
Closes #41

Built off of #76

Fixed up test coverage for that PR also

### CODE REVIEW

File: lib/index.js [hunk 1]
```diff
@@ -512,7 +563,7 @@ function createIntegrity (opts) {
   }
 }
 
-const NODE_HASHES = new Set(crypto.getHashes())
```
Comment (wraithgar) [inline lib/index.js:515]: Sets are slower to instantiate and only faster on lookups when we get into the thousands of entries.  On my machine this has 52 entries.

**Review by nlf — APPROVED** [review]
very nice cleanup and the fixes totally make sense
